import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch


def generate_pdf(messages: list, title: str = "RAG Conversation Export") -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=colors.HexColor("#002FA7"),
        spaceAfter=6,
        leading=24,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#52525B"),
        spaceAfter=20,
    )
    user_label_style = ParagraphStyle(
        "UserLabel",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#52525B"),
        fontName="Helvetica-Bold",
        spaceBefore=16,
        spaceAfter=4,
    )
    user_msg_style = ParagraphStyle(
        "UserMsg",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#09090B"),
        backColor=colors.HexColor("#F4F4F5"),
        leftIndent=10,
        rightIndent=10,
        spaceBefore=4,
        spaceAfter=8,
        leading=16,
    )
    ai_label_style = ParagraphStyle(
        "AILabel",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#002FA7"),
        fontName="Helvetica-Bold",
        spaceBefore=16,
        spaceAfter=4,
    )
    ai_msg_style = ParagraphStyle(
        "AIMsg",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#09090B"),
        spaceAfter=4,
        leading=16,
    )
    source_style = ParagraphStyle(
        "Source",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#52525B"),
        fontName="Helvetica-Oblique",
        spaceAfter=8,
    )

    story.append(Paragraph(title, title_style))
    story.append(
        Paragraph(
            f"Exported on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
            subtitle_style,
        )
    )
    story.append(
        HRFlowable(
            width="100%",
            thickness=2,
            color=colors.HexColor("#002FA7"),
            spaceAfter=20,
        )
    )

    for msg in messages:
        role = msg.get("role", "user")
        content = (
            msg.get("content", "")
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )

        if role == "user":
            story.append(Paragraph("YOU", user_label_style))
            story.append(Paragraph(content, user_msg_style))
        else:
            story.append(Paragraph("ASSISTANT", ai_label_style))
            story.append(Paragraph(content, ai_msg_style))
            sources = msg.get("sources", [])
            if sources:
                story.append(
                    Paragraph(f"Sources: {', '.join(sources)}", source_style)
                )
            confidence = msg.get("confidence", 0)
            if confidence:
                story.append(
                    Paragraph(
                        f"Confidence: {round(confidence * 100)}%", source_style
                    )
                )

    story.append(Spacer(1, 20))
    story.append(
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E4E4E7"))
    )
    story.append(
        Paragraph(
            "Generated by Adaptive Retrieval RAG System", source_style
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
